FROM ubuntu:latest

# Instalar dependencias necesarias
RUN apt-get update && \
    apt-get install -y \
    openjdk-11-jre-headless \
    curl \
    unzip \
    trimmomatic \
    fastqc \
    wget \
    spades \
    python3 \
    build-essential && \
    rm -rf /var/lib/apt/lists/*

# Descargar e instalar Nextflow
RUN curl -s https://get.nextflow.io | bash && \
    mv nextflow /usr/local/bin && \
    chmod +x /usr/local/bin/nextflow

# Establecer el directorio de trabajo
WORKDIR /workspace

