FROM ubuntu:latest

# Instalar dependencias necesarias
RUN apt-get update && \
    apt-get install -y \
    openjdk-11-jre-headless \
    curl \
    unzip \
    trimmomatic \
    fastqc \
    wget \
    spades \
    python3 \
    build-essential && \
    rm -rf /var/lib/apt/lists/*

# Python
ENV PYTHON=/usr/bin/python3

# Descargar e instalar Nextflow
RUN curl -s https://get.nextflow.io | bash && \
    mv nextflow /usr/local/bin && \
    chmod +x /usr/local/bin/nextflow

# Instalar SRA Toolkit
RUN wget "http://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/current/sratoolkit.current-ubuntu64.tar.gz" && \
    tar -zxvf sratoolkit.current-ubuntu64.tar.gz && \
    rm sratoolkit.current-ubuntu64.tar.gz && \
    mv sratoolkit.* /usr/local/bin/sratoolkit && \
    mv /usr/local/bin/sratoolkit/bin/* /usr/local/bin/

# Instalar Bowtie2 manualmente
RUN wget -O /tmp/bowtie2.tar.gz https://github.com/BenLangmead/bowtie2/releases/download/v2.4.4/bowtie2-2.4.4-linux-x86_64.zip && \
    unzip /tmp/bowtie2.tar.gz -d /usr/local/bin && \
    rm /tmp/bowtie2.tar.gz

# Agregar directorio de Bowtie2 al PATH
ENV PATH="/usr/local/bin/bowtie2-2.4.4-linux-x86_64:${PATH}"

# Instalar Kraken2 manualmente
RUN wget -O /tmp/kraken2.tar.gz https://github.com/DerrickWood/kraken2/archive/refs/tags/v2.1.2.tar.gz && \
    tar -zxvf /tmp/kraken2.tar.gz -C /usr/local/bin && \
    rm /tmp/kraken2.tar.gz && \
    cd /usr/local/bin/kraken2-2.1.2 && \
    ./install_kraken2.sh /usr/local/bin

# Agregar directorio de Kraken2 al PATH
ENV PATH="/usr/local/bin/kraken2-2.1.2:${PATH}"

# Instalar BLAST y HMMER
RUN apt-get update && \
    apt-get install -y ncbi-blast+ && \
    wget http://eddylab.org/software/hmmer/hmmer.tar.gz && \
    tar zxf hmmer.tar.gz && \
    cd hmmer-3.4 && \
    ./configure --prefix /usr/local && \
    make && \
    make check && \
    make install && \
    (cd easel; make install) && \
    rm -rf hmmer.tar.gz hmmer-3.4

# Instalar dependencias necesarias para compilar AMRFinder
RUN apt-get update && \
    apt-get install -y git build-essential libcurl4-openssl-dev

# Descargar AMRFinder desde GitHub
RUN git clone https://github.com/ncbi/amr.git /amrfinder && \
    cd /amrfinder && \
    make && \
    make install

# Ejecutar AMRFinder para descargar la base de datos
RUN amrfinder -u

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC

# Instala R y las herramientas de desarrollo necesarias
RUN apt-get update && \
    apt-get install -y --no-install-recommends r-base r-base-dev && \
    apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

# Instala el paquete devtools en R
RUN R -e "install.packages('devtools', repos='http://cran.rstudio.com/')"

# Instala el paquete XML en R
RUN R -e "install.packages('XML', repos='http://cran.rstudio.com/')"

# Descarga rentrez desde GitHub
RUN wget https://github.com/ropensci/rentrez/archive/refs/heads/master.tar.gz && \
    tar -zxvf master.tar.gz && \
    R CMD INSTALL rentrez-master/

# Instala los paquetes stringr y ape en R
RUN R -e "install.packages(c('stringr', 'ape'), repos='http://cran.rstudio.com/')"

RUN apt-get update && apt-get install -y autoconf

# Instala VCFtools desde el código fuente
RUN git clone https://github.com/vcftools/vcftools.git && \
    cd vcftools && \
    ./autogen.sh && \
    ./configure && \
    make && \
    make install

RUN git clone https://github.com/lh3/bwa.git && \
    cd bwa && \
    make

# Descarga Picard Tools desde GitHub y establece los permisos de ejecución
RUN wget https://github.com/broadinstitute/picard/releases/download/2.26.5/picard.jar -O /usr/local/bin/picard.jar && \
    chmod +x /usr/local/bin/picard.jar

# vcflib
RUN apt-get install -y libvcflib-tools libvcflib-dev

# Agrega el repositorio de Ubuntu
RUN echo "deb http://cz.archive.ubuntu.com/ubuntu jammy main universe" >> /etc/apt/sources.list

# Actualiza la lista de paquetes e instala freebayes
RUN apt-get update && \
    apt-get install -y freebayes

# Instalar paquetes de R
RUN R -e "install.packages('vcfR', repos='http://cran.rstudio.com/')"

RUN apt-get update && \
    apt-get install -y bcftools

# Instalar dependencias
RUN apt-get update && apt-get install -y \
    libdatetime-perl \
    libxml-simple-perl \
    libdigest-md5-perl \
    git \
    default-jre \
    bioperl

# Instalar BioPerl usando cpan
RUN cpan Bio::Perl

# Descargar el paquete libidn11
WORKDIR /downloads
RUN apt install -y wget && \
    wget http://mirrors.kernel.org/ubuntu/pool/main/libi/libidn/libidn11_1.33-2.2ubuntu2_amd64.deb

# Instalar el paquete libidn11
RUN apt install -y ./libidn11_1.33-2.2ubuntu2_amd64.deb

######################################
######################################
######################################
######################################
RUN apt-get install -y python3-pip python3-venv
RUN wget https://files.pythonhosted.org/packages/47/00/175bbbed1622d73778882b66f280fce8b1914bdbd7337dee91c8790becd9/resfinder-4.5.0.tar.gz && \
    tar -xzvf resfinder-4.5.0.tar.gz

RUN python3 -m venv myenv && \
    . myenv/bin/activate && \
    myenv/bin/pip install ./resfinder-4.5.0

# Clonar las bases de datos de ResFinder
RUN git clone https://bitbucket.org/genomicepidemiology/resfinder_db/ \
    && git clone https://bitbucket.org/genomicepidemiology/pointfinder_db/ \
    && git clone https://bitbucket.org/genomicepidemiology/disinfinder_db/

######################################
######################################
######################################
######################################

# Establecer el directorio de trabajo
WORKDIR /workspace

# java -jar /usr/local/bin/picard.jar